// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlanxdvyynqrtcifwnfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsYW54ZHZ5eW5xcnRjaWZ3bmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjUwMjEsImV4cCI6MjA3MTMwMTAyMX0.Z10JCC4q-Clj-Jal4jqj_mmkTUs3JlKpFGPJYXKOJ9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});